- cdf-pentaho5/build-res/cdf.build.js
- jQuery needs to be loaded before Bootstrap, fix load issue by adding bootstrap libs to the (compression) exclude list
- Avoid compressing Sprintf, Utils and Utf8Encoder because they need to be accessible to other AMD modules (e.g. AddIns) that don't depend on a main dashboard module (e.g. Dashboard.Blueprint)
> [CDF-334] - Compilation / Minification

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.views.js
- cdf-core/cdf/js-modules/dashboard/RefreshEngine.js
- cdf-core/config/context.js
- cdf-pentaho5/cdf/js-modules/dashboard/Dashboard.views.ext.js
- cdf-pentaho5/config/context.js
- Fixed references to deprecated Dashboards object in RefreshEngine
- Updated Dashboard.views according to the new RESTful Views API
- Included Base64 in the require lib cfg file
- updated SESSION_LOCALE in context.js used during unit tests
> [CDF-328] - Add support for Require.js in CDF

- cdf-core/cdf/js/Dashboards.Utils.js
We are storing the current locale and setting it after the configuration is done, because moment starts using the new locale after that and we just want to configure it for later use.
> [CDF-355] Enable configLanguage to also configure moment locale

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/cdf/js-lib/dataTables/css/jquery.dataTables_themeroller.css
- cdf-core/resource/resources.legacy.properties
- cdf-core/resource/resources.properties
- Added jquery.dataTables_themeroller.css to be used by the TableComponent when in the CDE editor the "Style" advanced property has the value "New" (a.k.a TableComponent.chartDefinition.tableStyle = "themeroller").
> [CDF-331] - Create a module for each component

- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/63-PentahoReportingComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/63-PentahoReportingComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/63-PentahoReportingComponent/template.html
Changed the report in the 5.x sample to:
- /public/Steel Wheels/Widget Library/Report Snippets/InventorybyLine.prpt
On the 4.x sample the report already could be exported to CSV and Text
> [CDF-524] Change sample on prptComponent to point to other report

- cdf-core/config/karma.ci.conf.legacy.js
@pamval I ran the karma tests on my machine and they all had passed, but I was alerted now by @afrjorge that sometimes some legacy tests are not executed. That was why this problem was not caught before the previous merge. please review
> [CDF-512] missing lib in karma legacy config file

- cdf-core/test-js/dashboard/Utils-spec.js
- cdf-core/test-js/legacy/core-spec-legacy.js
@pamval Tests for dateParse were checking the time zone of the resulting date, because CI server is on a different time zone, it made the tests fail. please review
> [CDF-512] Changed test so that they don't test the timezone in the resulting date

- cdf-core/cdf/js-modules/components/UnmanagedComponent.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.notifications.js
Some subtle (imo desirable) differences result from the revised implementation:
1. "cdf:postFetch" event receives the data instance already processed by `postFetch` method; this was already the case when the user modified the same data instance, but not if he would return a different instance.
2.  `drawTooltip` and `showTooltip` are now called in all lifecycle, instead of just in the synchronous one (and dashboard managed lifecycle), as long as a component has an `htmlObject`
This commit only refactors the "js-modules" CDF implementation.
@pamval please review.
> [CDF-540] - Refactor the UnmanagedComponent lifecycle handlers

- cdf-core/cdf/js-modules/components/DateInputComponent.css
This file was not included in last pull request and has the css rules for the require Date Input Component
> [CDF-546] adding missing css file for require Date Input Component

- cdf-core/test-js/components/FreeformComponent-spec.js
- cdf-core/test-js/dashboard/Dashboard.views-spec.js
- cdf-pentaho5/config/cdf.build.compile.js
- although it's already implicitly included, explicitly include XmlaQuery.js in the build configuration file for consistency
- make XmlaQuery.ext (endpoint) available to other resources, by excluding it from the main Dashboard.* compiled files, including it as a minified file in the compressed folder (for consistency with all other endpoints)
> [CLEANUP][CDF-571]

- cdf-core/cdf/js-modules/components/filter/views/Root.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/views/Root.js
- fixed 'alwaysExpanded' behaviour
- was: 'alwaysExpanded' became the active behaviour *after* the first onClick event in the component
- now: 'alwaysExpanded' behaviour  active right at initialize/render
> [CDF-579] Integrate new Selector component into CDF

- cdf-core/cdf/js-modules/components/ButtonComponent.js
- cdf-core/cdf/js/cdf.legacy.css
- cdf-core/cdf/js/components/input.js
- cdf-core/test-js/components/ButtonComponent-spec.js
- moved successCallback and errorCallback outside of the click callback function, avoids adding a new closure function per click
- added missing CSS styling in CDF 5.x legacy version
- fixed ReferenceError in unit test
> [CDF-236] Clicking many times on a Button Component in a short period of time triggers many server-side actions

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/cdf/js-modules/cdf-core-require-js-cfg.js
- Adding the ability to fully configure paths for CDF in test environment.
It is done via externally include the map:
var ENVIRONMENT_CONFIG = {
paths: {
"cdf": "../../build-res/module-scripts/cdf/js",
"cdf/lib": "../../build-res/module-scripts/cdf/js/lib"
}
};
That allows an arbitrary location for the cdf code, making the require paths work no mater of there is the cdf root
> [BACKLOG-4055]

- cdf-core/test-js/components/ButtonComponent-spec.js
- the previous commit didn't solve the problem of the failing test, which is the fact that enable() is now called when the buttonComponent is constructed and not just after being clicked. Updated the unit test accordingly;
> [TEST] - Fixed failing test

- cdf-core/cdf/js-modules/components/filter/controllers/Manager.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/controllers/Manager.js
- when only one Sorting Addin is being used don't convert the resulting value into a String
> [CDF-677] SortByValue incorrect results

- cdf-core/cdf/js-modules/components/filter/styles/filter.css
- cdf-core/cdf/js/components/filter/styles/filter.css
- cdf-core/resource/resources/style/template.css
- made legacy and amd versions of filter.css equal, according to the UX team's guidelines
- made template.css body rules more specific so AMD samples don't have overridden styles (e.g. font-family overridden by screen.css in a blueprint dashboard)
> [CDF-688] FilterComponent - filter.css is not the same in the legacy and amd versions of the component

- core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
- core-js/src/main/javascript/cdf/queries/BaseQuery.js
- core-js/src/test/javascript/cdf-legacy/queries/coreQueries-spec-legacy.js
- core-js/src/test/javascript/cdf/queries/BaseQuery-spec.js
- core-js/src/test/javascript/config/karma.conf.legacy.js
- removed duplicate error callback, added missing arguments parameter in CDF AMD version and updated tests
- allow CDF legacy non-CI karma tests to execute multiple times
- fixed path for cdf-base resource in non-CI legacy karma configuration file
> [CLEANUP, TEST]

- core-js/src/doc/javascript/config/customPlugins/defineTags.js
- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/tmpl/code.tmpl
- core-js/src/doc/javascript/template/tmpl/container.tmpl
- core-js/src/doc/javascript/template/tmpl/details.tmpl
- core-js/src/doc/javascript/template/tmpl/member-details.tmpl
- core-js/src/doc/javascript/template/tmpl/members-summary.tmpl
- core-js/src/doc/javascript/template/tmpl/method-details.tmpl
- core-js/src/main/javascript/cdf/dashboard/Popups.js
[BACKLOG-6478] - Fixed template topics like:
- Added new tag: code; to allow different case then example
- Removed unneeded buttons for show/hide of Private, Inherited and Deprecated Class members
- Fixed Method details template for Source Links
- Removed duplicated code from member-details, using details (the correct one) instead
- Updated method details for constructor, if that class is static and no constructor is needed
- Updated Constructor location in the Class Page
> [CDF-827] - Added documentation for inner objects on Popup components

- core-js/src/main/javascript/cdf/dashboard/Dashboard.lifecycle.js
- core-js/src/test/javascript/cdf/dashboard/Dashboard.lifecycle-spec.js
- avoid adding the "PostInitMarker" component more than once
> [BACKLOG-6345] WD: add component: duplicate component name 'PostInitMarker' error appear in browser's console while reopening dashboard

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/63-PentahoReportingComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/63-PentahoReportingComponent/template.html
- Set priority in Pentaho Reporting Component sample components. The select component must always execute before the reporting component.
> [CDF-871] PrptComponent sample executes the components in an arbitrary order

- core/src/main/java/org/pentaho/cdf/storage/StorageEngine.java
- core/src/main/java/org/pentaho/cdf/storage/StorageEngineInterface.java
- pentaho/src/main/java/org/pentaho/cdf/storage/ImpersonationHandler.java
- pentaho/src/main/java/org/pentaho/cdf/storage/StorageApi.java
- pentaho/src/test/java/org/pentaho/cdf/storage/ImpersonationHandlerTest.java
- pentaho/src/test/java/org/pentaho/cdf/storage/StorageApiTest.java
An impersonation guard has been implemented allowing users with admin role to work on behalf of other users.
The logic is encapsulated in the new ImpersonationHandler class which is called from StorageApi.impersonate() method.
In order to enable testability new class StorageEngineInterface is introduced and StorageEngine.setMockInstance() method
is added, which allows to provide mock for StorageEngine (the same way as this is implemented in
org.pentaho.platform.engine.security.SecurityHelper)
> [CDF-896] - CDF Storage: any user is able to change the storage of another user

- core-js/src/test/javascript/cdf-legacy/components/input-spec-legacy.js
- core-js/src/test/javascript/cdf/components/CommentsComponent-spec.js
- core-js/src/test/javascript/cdf/components/MultiButtonComponent-spec.js
- `describe` blocks don't support the `done` parameter
- synchronous tests don't need the `done` parameter
> [TEST] reviewed the usage of the optional "done" argument for async tests

- pentaho/src/main/java/org/pentaho/cdf/CdfApi.java
- pentaho/src/test/java/org/pentaho/cdf/CdfApiTest.java
[CDF-949] CDF: Embeded Dashboards returns HTTP even when the connection is done through SSL/TLS (https)
-added using scheme for HTTP protocol
-added tests
@pamval Could you please review and merge it?
> [CDF-949] CDF: Embeded Dashboards returns HTTP even when the connection is done through SSL/TLS (https)

- pentaho/src/main/java/org/pentaho/cdf/CdfApi.java
- pentaho/src/test/java/org/pentaho/cdf/CdfApiTest.java
[SP-3201][CDF-949] CDF: Embeded Dashboards returns HTTP even when theconnection is done through SSL/TLS (https)
-added using scheme for HTTP protocol
-added tests
> [SP-3201][CDF-949] CDF: Embeded Dashboards returns HTTP even when theconnection is done through SSL/TLS (https)

- pentaho-js/src/test/javascript/cdf/components/ccc/BaseCccComponent.ext-spec.js
@dcleao please review
removed this check because boxplot is no longer a black listed chart
> [BACKLOG-14077] - Fixed unit test

- core-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.js
- Added special case for an array property, which should be smashed if the array is empty. This will be reviewed if we have more properties like this in the future
@pamval @dcleao @afrjorge please review
> [BACKLOG-14077] 

- core-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.js
@afrjorge @lgrill-pentaho @hbfernandes pls review
this fixes the `mvn site` getting stuck
> [ENGOPS-3041] ignoring the BaseCcc component from the generated doc.

- core-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.js
- pentaho-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.ext.js
- pentaho-js/src/test/javascript/cdf/components/ccc/BaseCccComponent.ext-spec.js
- Reviewed chart naming conversion to handle area chart
- Reviewed color override taking into account vizApi.conf declares a color for MetricDocAbstract charts
@dcleao please review
> [BACKLOG-14077]

- pentaho/src/main/java/org/pentaho/cdf/CdfApi.java
- added new public method which can handle "secure" param through DI
- old method was rewritten in order to call the new one
> [CDE-908] Embedding a CDE dashboard fails when using HTTPS

- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/MultiButtonComponent.js
- core-js/src/main/javascript/cdf/components/SelectBaseComponent.js
- core-js/src/main/javascript/cdf/components/SelectComponent.js
- core-js/src/main/javascript/cdf/components/ToggleButtonBaseComponent.js
- core-js/src/test/javascript/cdf/components/ToggleButtonBaseComponent-spec.js
- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
> [PDB-1987] Check box filters with no default value set, display the first checkbox as selected

- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/MultiButtonComponent.js
- core-js/src/main/javascript/cdf/components/SelectBaseComponent.js
- core-js/src/main/javascript/cdf/components/SelectComponent.js
- core-js/src/main/javascript/cdf/components/ToggleButtonBaseComponent.js
- core-js/src/test/javascript/cdf/components/ToggleButtonBaseComponent-spec.js
- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
> [SP-3990][PDB-1987] Check box filters with no default value set, display the first checkbox as selected

- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/MultiButtonComponent.js
- core-js/src/main/javascript/cdf/components/SelectBaseComponent.js
- core-js/src/main/javascript/cdf/components/SelectComponent.js
- core-js/src/main/javascript/cdf/components/ToggleButtonBaseComponent.js
- core-js/src/test/javascript/cdf/components/ToggleButtonBaseComponent-spec.js
- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
> [SP-3989][PDB-1987] Check box filters with no default value set, display the first checkbox as selected

- pentaho-js/src/main/javascript/cdf/components/TableComponent.js
After doing tests to this CDE sample, they showed that CDF TableComponent was the major culprit in the memory leak. In each component update, when new data was received, the previous DataTable was not disposed, causing the memory leak in the sample.
The chart component also seemed to have some memory leaks, but when talking with @dcleao, we concluded that the extra memory allocation might be caused by protovis internal cache (for text values and such)
> [BACKLOG-25639] Real time sample dashboard has memory leaks

- pentaho/src/main/java/org/pentaho/cdf/context/ContextEngine.java
The second parameter of an InterPluginCall expects a valid method that exists in the class.
Originally someone passed in "" or no method, this caused the method compare to fail and gave a false report that CDA was not installed.
listQueries is a valid method for CDA, and thus will have the check work and return true.
AutoInclude logic works and was unmodified.
> [CDF-1024] CPF InterPluginCall changed causing CDF autoIncludes to fail.

- core-js/src/main/javascript/lib/i18n/cdf.jquery.i18n.js
Our environment locale is being lowercased here: https://github.com/pentaho/pentaho-platform-plugin-common-ui/blob/master/impl/client/src/main/javascript/web/pentaho/environment/impl/Environment.js#L64 
So, we need to do the same here, if we want a successful match. But we need to return the supported cased locale to download the wanted properties file.
> [CDE-1005] CDE dashboard can't be localized at country level

- core/pom.xml
@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removing dependency due to being marked as unused and declared via dependency:analyze (core/pom.xml)
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- https://github.com/pentaho/data-access/pull/1060
- https://github.com/pentaho/maven-project-archetypes/pull/16
- https://github.com/pentaho/maven-project-archetypes-ee/pull/35
- https://github.com/pentaho/modeler/pull/356
- …
> [PDI-17794] Warnings in Spoon console due to wrong version of log4j

- core-js/src/main/javascript/lib/theme/cupertino/jquery-ui-1.10.4.custom.css
- core-js/src/main/javascript/lib/theme/smoothness/jquery-ui-1.10.4.custom.css
with the update of JQuery in PPP-4008, JQuery-UI was also updated to version 1.12.1. 
Since we have custom CSS files based on JQuery-UI 1.10.4 (that were already tweeked) we need to re-adapt to the new version.
@pentaho-lmartins
> [CDE-1029] CDE - Datasources Panel layout - XPATH Queries not selected

- core/pom.xml
- core/src/main/java/org/pentaho/cdf/comments/CommentsEngine.java
- core/src/main/java/org/pentaho/cdf/storage/StorageEngine.java
- pentaho/pom.xml
- pentaho/src/main/java/org/pentaho/cdf/CdfApi.java
- pentaho/src/main/java/org/pentaho/cdf/CdfContentGenerator.java
- pentaho/src/main/java/org/pentaho/cdf/GetCDFResource.java
- pentaho/src/main/java/org/pentaho/cdf/ResourcesApi.java
- pentaho/src/main/java/org/pentaho/cdf/comments/CommentsApi.java
- pentaho/src/main/java/org/pentaho/cdf/context/ContextApi.java
- pentaho/src/main/java/org/pentaho/cdf/settings/SettingsApi.java
- pentaho/src/main/java/org/pentaho/cdf/storage/StorageApi.java
- pentaho/src/main/java/org/pentaho/cdf/util/CdfHttpServletRequestWrapper.java
- pentaho/src/main/java/org/pentaho/cdf/util/Parameter.java
- pentaho/src/main/java/org/pentaho/cdf/xactions/ActionEngine.java
- pentaho/src/test/java/org/pentaho/cdf/CdfApiTest.java
- pentaho/src/test/java/org/pentaho/cdf/comments/CommentsApiForTests.java
- pentaho/src/test/java/org/pentaho/cdf/comments/CommentsApiTest.java
- pentaho/src/test/java/org/pentaho/cdf/context/ContextApiForTests.java
- pentaho/src/test/java/org/pentaho/cdf/context/ContextApiTest.java
- pentaho/src/test/java/org/pentaho/cdf/settings/SettingsApiTest.java
- pentaho/src/test/java/org/pentaho/cdf/storage/StorageApiForTests.java
- pentaho/src/test/java/org/pentaho/cdf/storage/StorageApiTest.java
- pom.xml
[BACKLOG-41287]-Upgrading cdf from Java-EE to Jakarta-EE support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41287]-Upgrading cdf from Java-ee to Jakarta-ee support with Tomcat-10.X

- assemblies/cdf/pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

- pentaho/src/test/java/org/pentaho/cdf/settings/SettingsApiTest.java
[BACKLOG-46173]-Fixing cdf master build failure
[BACKLOG-46173]: https://hv-eng.atlassian.net/browse/BACKLOG-46173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-46173]-Fixing cdf master build failure

- assemblies/cdf/pom.xml
**Update Resource Filtering in Maven Build**
Modified the resource section to exclude image file types (*.icns, *.png, *.jpg, *.gif) from being included in resource processing.
This prevents unnecessary binary/image files from being processed or packaged unintentionally, improving build efficiency and artifact cleanliness.
With JDK 21, Maven and its plugins enforce stricter resource processing rules and improved validation during the build lifecycle. This can cause previously ignored or loosely handled files—such as images (*.png, *.jpg, etc.)—to:
Be unexpectedly processed or filtered, potentially causing build warnings or errors if binary files are filtered as text.
Trigger encoding or filtering issues, especially when filtering is enabled globally but not all resources are compatible …
> [BACKLOG-43902]-Java 21 : compatibility check for Pentaho and fix Build and Run time issues while building / testing
