- cdf-core/cdf/js/Dashboards.Utils.js
- cdf-core/resource/default-dashboard-template.html
- cdf-core/resource/template-dashboard-clean.html
- cdf-core/resource/template-dashboard-mantle.html
- cdf-core/resource/template-dashboard.html
> [CDF-458]: Build capability to format numbers into CDF

- cdf-pentaho5/cdf/js/components/Pentaho.Reporting.js
> [CDF-471] - Remove SchedulePrptComponent scheduleRequest's implicit global

- cdf-core/cdf/js/components/input.js
> [CDF-474] - changed dropdownAutoWidth existence verification

- cdf-core/cdf/js/Dashboards.Utils.js
> [CDF-458]: Added fallback logic to language provider

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/cdf/js-lib/require-amd/nonamd.js
- cdf-core/cdf/js-lib/require-text/text.js
- cdf-core/cdf/js-modules/components/SelectBaseComponent.js
- cdf-core/cdf/js-modules/components/ToggleButtonBaseComponent.js
- cdf-core/cdf/js/components/input.js
- Added RequireJS text! loader plugin version 2.0.14
- Added RequireJS amd! loader plugin
> [CDF-485] - Add support for the RequireJS amd! loader plugin

- cdf-core/cdf/js-modules/cdf-core-require-js-cfg.js
- Remove cache-buster when running in debug mode
> [CDF-328] - Add support for Require.js in CDF

- cdf-core/cdf/js-modules/dashboard/Utils.js
- cdf-core/cdf/js/Dashboards.Utils.js
> [CDF-355] Enable configLanguage to also configure moment locale

- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/format.html
- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/format.xcdf
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/format.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/format.xcdf
> [CDF-458] Added documentation on how to format numbers and dates in CDF

- cdf-core/cdf/js-modules/dashboard/Utils.js
- cdf-core/cdf/js/Dashboards.Utils.js
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf-require/30-documentation/format.html
> [CDF-355] enable dateFormat to receive a object with a custom date

- cdf-pentaho5/solution/plugin-samples/pentaho-cdf-require/30-documentation/format.html
> [CDF-355]: updated code documentation to require

- cdf-pentaho5/build-res/cdf.build.js
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/50-dashboardtypes/4-clean/template.html
> [CDF-486] New Clean Dashboard Sample

- cdf-pentaho-base/src/org/pentaho/cdf/context/ContextEngine.java
> [CDF-501] Dashboards.context.params is not receiving the parameter defined in the URL

- build-res/subfloor-js.xml
- cdf-core/build.xml
- cdf-pentaho5/build.xml
- removed deprecated ant task attributes
- simplified ant target test-js
> [CDE-378] - Review build process with minification

- cdf-core/cdf/js-modules/dashboard/Dashboard.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.notifications.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.storage.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.views.js
@jvelasques more documentation
> [CDF-333] - Documentation for some of the dashboard modules

- cdf-pentaho5/build.xml
- cdf-pentaho5/config/cdf.build.compile.js
- moved configuration file into the config folder
> [CDF-334] - Compilation / Minification

- cdf-core/cdf/js-lib/cdf.css
- cdf-core/cdf/js/cdf.css
> [CDE-471] On Popup Component Reference dragging first popup results in it jumping to bottom of page

- cdf-core/cdf/js-modules/AddIn.js
- cdf-core/cdf/js-modules/Dashboard.Blueprint.js
- cdf-core/cdf/js-modules/Dashboard.Bootstrap.js
- cdf-core/cdf/js-modules/Dashboard.Clean.js
- cdf-core/cdf/js-modules/Logger.js
- cdf-core/cdf/js-modules/OlapUtils.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.addIns.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.legacy.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.lifecycle.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.notifications.js
- cdf-core/cdf/js-modules/dashboard/Utils.js
@jvelasques, fixed issues, review again
> [CDF-333] - API documentation for Logger

- cdf-core/cdf/js-modules/dashboard/Dashboard.notifications.js
- cdf-core/test-js/dashboard/Dashboard.notifications.ext.js
- cdf-pentaho5/cdf/js-modules/dashboard/Dashboard.notifications.ext.js
- cdf-pentaho5/config/cdf.build.compile.js
- cdf-pentaho5/test-js/dashboard/Dashboard.notifications.ext.js
- Added Ping endpoint for Dashboard.notifications, to be used by the function dashboard.checkServer()
> [CDF-376] - Check wd namespace and helpers usage

- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/concepts.xcdf
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/lifecycle.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/lifecycle.xcdf
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/templates.xcdf
- fixed template file references
- removed Mustache.compile deprecated function usage
> [CLEANUP] - legacy documentation

- cdf-core/build.properties
- cdf-core/build.xml
- cdf-core/cdf/js-modules/dashboard/Dashboard.lifecycle.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.notifications.js
- cdf-core/cdf/js-modules/dashboard/OptionsManager.js
- cdf-core/cdf/js-modules/dashboard/Popups.js
- cdf-core/cdf/js-modules/dashboard/Utf8Encoder.js
- cdf-pentaho/build.properties
- cdf-pentaho5/build.properties
@jvelasques @afrjorge please review
> [CDF-333] - Added yet more API documentation

- cdf-core/cdf/js-lib/require-amd/nonamd.js
- cdf-core/cdf/js-modules/components/BaseComponent.js
- cdf-core/cdf/js-modules/components/UnmanagedComponent.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.query.js
- cdf-core/cdf/js-modules/dashboard/Query.js
- cdf-core/cdf/js-modules/dashboard/RefreshEngine.js
- cdf-core/cdf/js-modules/dashboard/Sprintf.js
- cdf-core/cdf/js-modules/queries/BaseQuery.js
- cdf-core/cdf/js-modules/queries/CdaQuery.js
- cdf-core/cdf/js-modules/queries/CpkQuery.js
- cdf-core/cdf/js-modules/queries/LegacyQuery.js
@jvelasques yesterday reviews and added doc for BaseComponent and UnmanagedComponent
> [CDF-333] - Documentation for Queries and Base/Unmanaged component

- cdf-core/cdf/js/lib/backbone/backbone.js
- cdf-core/cdf/js/lib/base/Base.js
- cdf-core/cdf/js/lib/mustache/mustache.js
- cdf-core/cdf/js/lib/underscore/underscore.js
- legacy JS must avoid using libs that register themselves as AMD modules, adding pre-require versions to legacy source-code
> [CDF-328][CDF-492][CDF-329] - Move external libs to dedicated folder

- cdf-core/cdf/js-modules/dashboard/Utils.js
- cdf-core/cdf/js/Dashboards.Utils.js
- cdf-core/test-js/dashboard/Utils-spec.js
- cdf-core/test-js/legacy/core-spec-legacy.js
- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/format.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/format.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/format.html
Also updated CDF documentation to reflect the changes made
> [CDF-511][CDF-512] Reviewed dateFormat function and added dateParse function

- cdf-core/cdf/js/cdf.legacy.css
> [CDE-471] Added missing css code after require-js merge

- cdf-core/cdf/js-modules/components/CommentsComponent.js
- fixed interaction blockage
- fixed typo queyResult to queryResult
> [CDF-528] - Comments Component require sample after interacting with the sample a second interaction is blocked

- cdf-pentaho5/build.xml
> [CLEANUP] - Fixed bug with test compilation

- cdf-core/cdf/js-modules/addIns/colTypes/dataBar/dataBar.js
- cdf-core/cdf/js-modules/addIns/colTypes/pvSparkline/pvSparkline.js
- cdf-core/cdf/js-modules/components/ProtovisComponent.js
- cdf-core/cdf/js-modules/components/ccc/BaseCccComponent.js
- cdf-pentaho5/build.xml
> Future develop

- cdf-core/config/karma.ci.conf.legacy.js
- cdf-core/config/karma.conf.legacy.js
- cdf-core/test-js/legacy/core-spec-legacy.js
> [CDF-541] Fix cdf-core legacy unit tests

- cdf-core/cdf/js-modules/cdf-core-require-js-cfg.js
- cdf-core/cdf/js-modules/components/ccc/CccStackedDotChartComponent.js
> [CDF-331] - Create a module for each component - Fix module id of CccStackedDotChartComponent

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/test-js/legacy/components/visualization-spec-legacy.js
- cdf-pentaho-base/cdf/js-modules/components/VisualizationAPIComponent.js
- cdf-pentaho-base/cdf/js/components/VisualizationAPIComponent.js
- cdf-pentaho5/config/karma.ci.conf.js
- cdf-pentaho5/config/karma.conf.js
- cdf-pentaho5/config/require-config.js
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- cdf-pentaho5/test-js/components/VisualizationAPIComponent-spec.js
- cdf-pentaho5/test-js/mocks/common-ui/util/URLEncoder.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/VizController.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/data/DataTable.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/eventsManager.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/vizTypeRegistry.js
These commits should be accepted along with those in the CDE PR: https://github.com/webdetails/cde/pull/398.
@pamval please review.
> [BACKLOG-2540] - AMD Conversion

- cdf-core/resource/resources/languages/messages.properties
- cdf-core/resource/resources/languages/messages_en.properties
- reviewed default and English files
> BACKLOG-3306 - Checkin 5.4 Localization files from Acclaro (2nd drop)

- cdf-core/cdf/js-modules/queries/CdaQuery.js
- cdf-core/cdf/js-modules/queries/CpkQuery.js
- cdf-core/test-js/dashboard/Query-spec.js
@pamval @afrjorge please review
> [CDF-553] - Added unit tests to test queries with dashboard parameters

- cdf-pentaho5/src/org/pentaho/cdf/CdfApi.java
> [CDF-491] Remove GetHeaders endpoint from CDF's public api

- cdf-core/cdf/js-modules/components/QueryComponent.js
- cdf-core/cdf/js/components/core.js
- cdf-core/test-js/components/QueryComponent-spec.js
- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/70-QueryComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/70-QueryComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/70-QueryComponent/template.html
> [CDE-479] Include the 'unmanagedQueryComponent' as a standard CDE component

- cdf-core/cdf/js-lib/cdf.css
- cdf-core/cdf/js-modules/components/AutocompleteBoxComponent.css
- cdf-core/cdf/js-modules/components/AutocompleteBoxComponent.js
- cdf-core/cdf/js-modules/components/QueryComponent.js
- cdf-core/cdf/js/cdf.css
- cdf-core/cdf/js/cdf.legacy.css
- cdf-core/cdf/js/components/core.js
- cdf-core/cdf/js/components/input.js
- cdf-core/test-js/components/QueryComponent-spec.js
- [CDE-479] Fix bug when QueryComponent.makeQuery method was called from others components
- [CDF-531] Css fix and cleanup. also fixed bug where the input box was being cleared when it shouldn't
> [CDE-479][CDF-531]

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/cdf/js-modules/cdf-core-require-js-cfg.js
- disabled cache buster for AMD modules
> [CDF-569] - CDF should allow resources to be served by cache on reload

- cdf-core/cdf/js/components/core.js
> [CDE-479] Fix for legacy query component sync success callback function

- build-res/subfloor.xml
- cdf-core/build.properties
- cdf-core/cdf/js-modules/components/UnmanagedComponent.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.notifications.js
- cdf-core/ivysettings.xml
- cdf-core/test-js/legacy/components/visualization-spec-legacy.js
- cdf-pentaho-base/cdf/js-modules/components/VisualizationAPIComponent.js
- cdf-pentaho-base/cdf/js/components/VisualizationAPIComponent.js
- cdf-pentaho/build.properties
- cdf-pentaho/config/build.properties
- cdf-pentaho/ivysettings.xml
- cdf-pentaho5/build.properties
- cdf-pentaho5/config/build.properties
- cdf-pentaho5/config/karma.ci.conf.js
- cdf-pentaho5/config/karma.conf.js
- cdf-pentaho5/config/require-config.js
- cdf-pentaho5/ivy.xml
- cdf-pentaho5/ivysettings.xml
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- cdf-pentaho5/test-js/components/VisualizationAPIComponent-spec.js
- cdf-pentaho5/test-js/mocks/common-ui/util/URLEncoder.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/VizController.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/data/DataTable.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/eventsManager.js
- cdf-pentaho5/test-js/mocks/common-ui/vizapi/vizTypeRegistry.js
@pamval please review, included fix to [CDF-540] from @dcleao (duarte/master2 e8a4694e0f39480e9a80a0ca65293f5e03a1a212)
> merge future-develop branch into master (cherry-picks)

- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/20-samples/queries/MQL/index.properties
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/20-samples/queries/MQL/index.xml
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/20-samples/queries/MQL/mql.xcdf
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/20-samples/queries/MQL/mqlDash.cda
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/20-samples/queries/MQL/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/queries/MQL/index.properties
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/queries/MQL/index.xml
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/queries/MQL/mql.xcdf
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/queries/MQL/mqlDash.cda
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/queries/MQL/template.html
- added legacy and AMD samples
> [CDE-579] save CDA queries using CDATA sections

- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/map_dashboard/BarChart2.xaction
- added void(0) in the end of <url-template> CDATA section so firefox doesn't open a new window/tab when bar chart is clicked
> [CDF-588] Sample Map Dashboard returns error when clicking in a bar chart

- build.xml
- cdf-core/build.xml
- cdf-pentaho/build.xml
- cdf-pentaho5/build.xml
- overwrite subfloor default value 'no'
> [TEST] make build fail when junit test errors or failures occur

- cdf-core/cdf/js-modules/dashboard/Dashboard.parameters.js
- cdf-core/test-js/dashboard/Dashboard.parameters-spec.js
- Recovered functionality to allow flatParameters names in setParameter calls. Unit tests updated, testing the default behaviour and the new case
> [BACKLOG-4074]

- cdf-pentaho5/build.properties
- cdf-pentaho5/ivy.xml
- also moved all spring revisions to build.properties
> spring.security upgraded to 2.0.8.RELEASE

- cdf-core/cdf/js-modules/components/ButtonComponent.js
- cdf-core/cdf/js-modules/dashboard/Dashboard.js
- cdf-core/cdf/js/components/input.js
- cdf-pentaho-base/cdf/js-modules/components/TableComponent.js
- cdf-pentaho-base/cdf/js/components/table.js
- Adding a getter getWcdfSettings, for CDE to override
- Making Button and Table components default style tied to the rendererType
> [CDE-615] - ButtonComponent doesn't show label

- cdf-core/cdf/js-lib/cdf-core-lib-require-js-cfg.js
- cdf-core/cdf/js-modules/cdf-core-require-js-cfg.js
@afrjorge @dcleao please merge
picked from https://github.com/webdetails/cdf/commit/01395e1eecec0f3e772283cdac0683bf9e3a7f8d
> [SP-1957] - CDF should allow resources to be served by cache on reload

- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
* Changing VizAPI 3 visualization ids.
@pamval please review.
> [BACKLOG-4144] - Full VizAPI/Analyzer Support for 3rd-party, Legacy Visualizations

- cdf-core/cdf/js/components/input.js
- cdf-core/test-js/legacy/components/input-spec-legacy.js
Tests for mutlibutton component not added due to issues in test env accessing the mutlibutton prototype on https://github.com/webdetails/cdf/blob/master/cdf-core/cdf/js/components/input.js#L1156
> [CDF-655] - backport of BACKLOG-5349 to legacy js

- cdf-core/cdf/js-modules/components/MultiButtonComponent.js
- cdf-core/cdf/js-modules/components/ToggleButtonBaseComponent.js
- cdf-core/cdf/js/components/input.js
- cdf-core/test-js/components/CheckComponent-spec.js
- cdf-core/test-js/components/MultiButtonComponent-spec.js
- cdf-core/test-js/components/RadioComponent-spec.js
- cdf-core/test-js/legacy/components/input-spec-legacy.js
> 5.x - cherry pick

- cdf-core/src/org/pentaho/cdf/comments/CommentEntry.java
- cdf-core/src/org/pentaho/cdf/storage/StorageEntry.java
- cdf-core/src/org/pentaho/cdf/utils/JsonUtil.java
- cdf-core/test-src/org/pentaho/cdf/MessagesTest.java
- cdf-core/test-src/org/pentaho/cdf/comments/CommentEntryTest.java
- cdf-core/test-src/org/pentaho/cdf/environment/DefaultCdfEnvironmentTest.java
- cdf-core/test-src/org/pentaho/cdf/packager/CdfHeadersProviderTest.java
- cdf-core/test-src/org/pentaho/cdf/storage/StorageEntryTest.java
- cdf-core/test-src/org/pentaho/cdf/utils/JsonUtilTest.java
- Increased unit test coverage;
- Applied CheckStyle to existing classes;
> [BACKLOG-5384, TEST, CLEANUP] - Increase unit test coverage

- cdf-core/cdf/js-modules/components/filter/controllers/RootCtrl.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/controllers/RootCtrl.js
- fix TypeError when filter has no options to show
> [CDF-597] FilterComponent - search input behaviour when there's no match

- cdf-pentaho5/ivy.xml
> [CLEANUP] - Updating cpf version due to artefact cleanup

- cdf-core/cdf/js-modules/components/filter/templates/Root-footer.html
- removing some extra spaces that change the visual aspect of the UI when using the template HTML file
> [CDF-583] Refactor CDF's FilterComponent 'templates.js' to break it down into a set of moustache template files

- cdf-core/cdf/js-modules/components/filter/controllers/Manager.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/controllers/Manager.js
- cdf-core/test-js/components/FilterComponent-spec.js
- add support for multiple sorting functions
- added unit test
- added documentation
> [CDF-677, TEST, DOC] FilterComponent- SortByValue incorrect results

- cdf-core/cdf/js/components/input.js
- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
> [CDE-691] Autocomplete dropdown does not reappear after selection is made

- cdf-core/cdf/js/components/input.js
- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
> [CHERRYICK][CDE-691] Autocomplete dropdown does not reappear after selection is made

- cdf-core/cdf/js/components/input.js
- cdf-pentaho/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
> [CHERRYPICK][CDE-691] Autocomplete dropdown does not reappear after selection is made

- cdf-pentaho5/solution/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/92-FilterComponent/Filter-VisualGuide/template.html
Correction of one of the samples previously submitted.
> [CDF-691]-Filter Component - Visual guide sample inconsistencies

- cdf-core/cdf/js-modules/dashboard/Utils.js
- cdf-core/cdf/js/Dashboards.Utils.js
- cdf-core/test-js/dashboard/Utils-spec.js
- Check if inputs are allready escaped and not apply re-escaping to them.
- Added tests
@pamval, @dcleao, review it please
> [BISERVER-12840] - Accented Characters get encoded on Dropdown parameter ReportViewer

- pentaho/pom.xml
- Fixing cdf-core js artefact reference in cdf-pentaho build
> [ENGOPS-1578] - Converting CDF to maven:

- cdf-core/cdf/js-modules/dashboard/Utils.js
- cdf-core/cdf/js/Dashboards.Utils.js
- cdf-core/test-js/dashboard/Utils-spec.js
@jvelasques, @pamval, review it please. This is a backport of #673
> [SP-2241] - Backport of BISERVER-12840 - Accented Characters get encoded on Dropdown parameter ReportViewer (6.0 Suite)

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jfreechart-cda.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jfreechart.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jfreechart.xaction.sql
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jfreechartdial-cda.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jfreechartdial.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jfreechartdial.xaction.sql
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jpivot.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jtable-cda.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jtable.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/jtable.xaction.sql
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/kettletransformation.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/openflashchart.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/openflashchart.xml
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/timelineeventfeeder.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/timelinefeeder.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/timelinefeeder.xaction.sql
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/tmp_jfreechart.xaction
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/traffic.xaction
- core-js/src/test/javascript/config/karma.ci.conf.js
- core-js/src/test/javascript/config/karma.conf.js
- core-js/src/test/javascript/config/karma.conf.legacy.js
- pentaho-js/src/test/javascript/config/karma.ci.conf.js
- pentaho-js/src/test/javascript/config/karma.ci.conf.legacy.js
- pentaho-js/src/test/javascript/config/karma.conf.js
- pentaho-js/src/test/javascript/config/karma.conf.legacy.js
- Fixing preprocessors paths in ci configuration and removed preprocessors for local debug configs to avoid source compilation
- Updated paths for pentaho-js reports location
- Added wrongly removed actions folder from samples
> [CLEANUP] & [ENGOPS-1578]

- pom.xml
> [CLEANUP] - Added project.stage for version.xml generation

- cdf-core/cdf/js-modules/queries/BaseQuery.js
- cdf-core/cdf/js/queries/coreQueries.js
- cdf-core/test-js/legacy/queries/coreQueries-spec-legacy.js
- cdf-core/test-js/queries/BaseQuery-spec.js
- removed duplicate error callback
- updated tests
> [CLEANUP, TEST] cherry pick

- core-js/pom.xml
- pom.xml
@pamval @annapopova1 @krivera @afrjorge @plagoa @jvelasques please check
This can be executed using mvn clean site
> [CDF-728] - Added jsdoc plugin to cdf build

- core-js/pom.xml
- pentaho-js/pom.xml
- pom.xml
@pamval @afrjorge @jvelasques please review
> [CDF-728] - Fixed jsdoc paths

- core-js/src/main/javascript/cdf-core-lib-require-js-cfg.js
- replaced amd! loader plugin with shim configuration
> [CDF-456] Fix for backwards compatibility issue

- pom.xml
@afrjorge @pamval please review
> [CDF-728] - Fixed jsdoc config file path via maven resources filtering

- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/controllers/Manager.js
- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/controllers/RootCtrl.js
- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/defaults.js
- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/models/SelectionTree.js
- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/models/Tree.js
- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/views/Abstract.js
- core-js/src/main/javascript/cdf-legacy/components/filter/js/filter.js
- core-js/src/main/javascript/cdf/components/filter/FilterComponent.js
- core-js/src/main/javascript/cdf/components/filter/base/defaults.js
- core-js/src/main/javascript/cdf/components/filter/controllers/Manager.js
- core-js/src/main/javascript/cdf/components/filter/controllers/RootCtrl.js
- core-js/src/main/javascript/cdf/components/filter/views/Abstract.js
- core-js/src/main/javascript/lib/baseSelectionTree/BaseSelectionTree.js
- core-js/src/main/javascript/lib/baseSelectionTree/Tree.js
- core-js/src/test/javascript/cdf/components/FilterComponent-spec.js
> [CDF-664] FilterComponent: moved filtering capability from Manager to Model

- cdf-core/cdf/js-lib/baseSelectionTree/BaseSelectionTree.js
- cdf-core/cdf/js-lib/baseSelectionTree/Tree.js
- cdf-core/cdf/js-modules/components/filter/FilterComponent.js
- cdf-core/cdf/js-modules/components/filter/base/defaults.js
- cdf-core/cdf/js-modules/components/filter/controllers/Manager.js
- cdf-core/cdf/js-modules/components/filter/controllers/RootCtrl.js
- cdf-core/cdf/js-modules/components/filter/views/Abstract.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/controllers/Manager.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/controllers/RootCtrl.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/defaults.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/models/SelectionTree.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/models/Tree.js
- cdf-core/cdf/js/components/filter/js/TreeFilter/views/Abstract.js
- cdf-core/cdf/js/components/filter/js/filter.js
- cdf-core/test-js/components/FilterComponent-spec.js
> [CDF-664] FilterComponent: moved filtering capability from Manager to Model (backport to 5.x)

- core-js/src/main/javascript/cdf/components/AutocompleteBoxComponent.js
- core-js/src/main/javascript/cdf/components/QueryComponent.js
> [TEST] - Fixing unintended changes from JsDoc conversion

- core-js/package.json
- core-js/src/main/javascript/cdf/dashboard/Container.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.bookmarkable.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.views.js
- pentaho-js/package.json
- removed yuidoc references
- removed unnecessary variable initialisations
- moved the Container class description into the appropriate JSDoc tag
> [CLEANUP, DOC]

- core-js/src/doc/javascript/template/tmpl/details.tmpl
- core-js/src/doc/javascript/template/tmpl/layout.tmpl
- core-js/src/doc/javascript/template/tmpl/modifier.tmpl
- core-js/src/doc/javascript/template/tmpl/modifiers.tmpl
- core-js/src/doc/javascript/template/tmpl/params.tmpl
- core-js/src/doc/javascript/template/tmpl/properties.tmpl
- Updated tables and badge according with last ux feedback
- Fixed double depredated information in details
@pamval @afrjorge @jvelasques please review
> [BACKLOG-6478] - Fixed template topics like:

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/20-samples/prpt_sample/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/prpt_sample/template.html
@afrjorge @jvelasques @pamval please review
> [BACKLOG-6026] - Updated links for Product Sales prpt

- core-js/src/main/javascript/cdf/_doc/events.jsdoc
- core-js/src/main/javascript/cdf/components/BaseComponent.js
- core-js/src/main/javascript/cdf/components/UnmanagedComponent.js
- core-js/src/main/javascript/cdf/components/_doc/events.jsdoc
- core-js/src/main/javascript/cdf/dashboard/Dashboard.components.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.lifecycle.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.parameters.js
- core-js/src/main/javascript/cdf/dashboard/_doc/events.jsdoc
- associate events with the class instances they belong to
- exposed dashboard.logLifecycle flag
- typos
- replaced <br> with <p>
- added summary tag for events
> [CDF-829] improve event documentation

- core-js/src/doc/javascript/template/tmpl/container.tmpl
- core-js/src/doc/javascript/template/tmpl/method-details.tmpl
- core-js/src/doc/javascript/template/tmpl/returns.tmpl
- Updated main class page, removing unneeded div containers
- Updated returns section to reflect last ux feedback
@afrjorge @jvelasques please review
> [BACKLOG-6478]

- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/tmpl/details.tmpl
- core-js/src/doc/javascript/template/tmpl/modifiers.tmpl
- core-js/src/main/javascript/cdf/dashboard/Dashboard.parameters.js
[BACKLOG-6478]
- Fixed default value representation for members
- Fixed constant badge not showing due to jsdoc json overrides
@afrjorge @jvelasques @pamval please review
> [CDF-834] - Added documentation for Dashboard.parameters

- core-js/src/main/javascript/cdf/dashboard/Dashboard.query.js
> [CDF-839] - Added documentation for Dashboard.query object

- core-js/src/main/javascript/cdf/components/UnmanagedComponent.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.views.js
[CDF-842] - Added type and protected to the viewParameters object
@afrjorge please view
> [CDF-842] & [CDF-843] & [CDF-845]

- core-js/src/main/javascript/cdf/dashboard/Dashboard.legacy.js
@diogofscmariano please review
> [CDF-846] Increase documentation for Dashboard.legacy

- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/static/styles/prettify-tomorrow.css
@graimundo @diogofscmariano please review
> [BACKLOG-6477] Create the index / navigation for JS API reference in Mindtouch

- core-js/src/doc/javascript/config/jsdoc-cdf.json
- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/tmpl/details.tmpl
- pom.xml
- added dynamic link to github class pages
> [BACKLOG-6478] - Create the Class page for JS API reference in Mindtouch

- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/tmpl/container.tmpl
@diogofscmariano @jvelasques @afrjorge please review
> [DOC] Including changes mande to the jsdoc template in common-ui

- core-js/src/main/javascript/cdf-legacy/components/core.js
- core-js/src/main/javascript/cdf/components/CommentsComponent.js
- bind the callback contained in commentsUpdateNotification to the appropriate context
> [CDF-868] TypeError in Comments Component

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/20-samples/sample_dashboard_broadcast/template.html
- Added missing jquery dependency to the broadcast sample.
> [CDF-872] Missing dependency in the CDF AMD broadcast sample

- core-js/src/main/javascript/cdf/AddIn.js
- core-js/src/main/javascript/cdf/README.md
- core-js/src/main/javascript/cdf/_doc/events.jsdoc
- core-js/src/main/javascript/cdf/components/BaseComponent.js
- core-js/src/main/javascript/cdf/components/_doc/events.jsdoc
- core-js/src/main/javascript/cdf/dashboard/Dashboard.addIns.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.bookmarkable.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.components.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.context.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.dataSources.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.legacy.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.lifecycle.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.notifications.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.parameters.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.query.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.storage.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.views.js
- core-js/src/main/javascript/cdf/dashboard/Popups.js
- core-js/src/main/javascript/cdf/dashboard/Query.js
- core-js/src/main/javascript/cdf/dashboard/RefreshEngine.js
- core-js/src/main/javascript/cdf/dashboard/Utf8Encoder.js
- core-js/src/main/javascript/cdf/dashboard/Utils.js
- core-js/src/main/javascript/cdf/queries/BaseQuery.js
- core-js/src/main/javascript/cdf/queries/CdaQuery.js
- core-js/src/main/javascript/cdf/queries/XmlaQuery.js
> [CDF-822] - DOC: Review the CDF API javascript documentation for correctness

- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/tmpl/amd.tmpl
- core-js/src/doc/javascript/template/tmpl/container.tmpl
- core-js/src/doc/javascript/template/tmpl/details.tmpl
- core-js/src/doc/javascript/template/tmpl/events-summary.tmpl
- core-js/src/doc/javascript/template/tmpl/layout.tmpl
- core-js/src/doc/javascript/template/tmpl/member-details.tmpl
- core-js/src/doc/javascript/template/tmpl/members-summary.tmpl
- core-js/src/doc/javascript/template/tmpl/method-details.tmpl
- core-js/src/doc/javascript/template/tmpl/methods-summary.tmpl
- core-js/src/doc/javascript/template/tmpl/params.tmpl
- core-js/src/doc/javascript/template/tmpl/type.tmpl
- core-js/src/main/javascript/cdf/Dashboard.Blueprint.js
- core-js/src/main/javascript/cdf/Dashboard.Bootstrap.js
- core-js/src/main/javascript/cdf/components/_doc/events.jsdoc
- core-js/src/main/javascript/cdf/dashboard/Dashboard.addIns.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.bookmarkable.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.components.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.context.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.dataSources.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.i18n.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.legacy.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.lifecycle.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.notifications.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.parameters.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.query.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.storage.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.views.js
- core-js/src/main/javascript/cdf/dashboard/_doc/events.jsdoc
- fixed links and other minor documentation improvements
> [BACKLOG-7174] Handle potencial last minute changes

- core-js/src/test/javascript/cdf-legacy/unmanaged-spec-legacy.js
- core-js/src/test/javascript/cdf/dashboard/Dashboard.notifications-spec.js
@diogofscmariano @jvelasques please review
> [BACKLOG-6856] Tests for blockUI behaviour

- pentaho-js/src/main/javascript/cdf-legacy/components/table.js
- pentaho-js/src/main/javascript/cdf/components/TableComponent.js
- pentaho-js/src/test/javascript/cdf/components/TableComponent-spec.js
- fix for legacy queries (non-CDA)
> [BACKLOG-8006] -  Table Component cannot updated if paginate Server side

- core-js/src/test/javascript/config/karma.ci.conf.js
- core-js/src/test/javascript/config/karma.conf.js
- pentaho-js/src/test/javascript/config/karma.ci.conf.js
- pentaho-js/src/test/javascript/config/karma.conf.js
@diogofscmariano @pamval please review
> [TEST] Add HTML coverage reports

- core-js/src/main/javascript/cdf/components/filter/HtmlUtils.js
- core-js/src/main/javascript/cdf/components/filter/data-handlers/InputDataHandler.js
- core-js/src/main/javascript/cdf/components/filter/views/Abstract.js
- core-js/src/test/javascript/cdf/components/FilterComponent-spec.js
@velasques, @diogofscmariano, @pamval, could you please take a look? - the fix is without tests since the issue is the blocker for codefreeze. Tests will be provided later.
> [CDE-837] - FilterComponent - html injection

- core-js/src/main/javascript/cdf/components/MultiButtonComponent.js
- core-js/src/test/javascript/cdf/components/MultiButtonComponent-spec.js
Added a new case to dashboard.fireChange() call condition in MultiButtonComponent.js#draw() function.
@pamval , @jvelasques please review.
> [PDB-1901] Filters used in Analyzer reports are not updated when using Dashboard buttons especially when the value of the buttons change

- pentaho/src/test/java/org/pentaho/cdf/storage/StorageApiTest.java
> [CDF-896] - CDF Storage: any user is able to change the storage of another user

- cdf-pentaho5/cdf/js/cdf-base.js
@mbatchelor, @pamval, @jvelasques, essentially it's additional PR for http://jira.pentaho.com/browse/SP-2855. Thanks.
> [BACKLOG-10615] - Dashboards plugin is not functional

- pentaho-js/src/main/javascript/cdf-legacy/components/Pentaho.Analyzer.js
- pentaho-js/src/main/javascript/cdf/components/AnalyzerComponent.js
> Revert "[CDF-887] - Date Range input not able to pass parameter correctly to …"

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/90-AnalyzerComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/90-AnalyzerComponent/template.html
- pentaho-js/src/main/javascript/cdf-legacy/components/Pentaho.Analyzer.js
- pentaho-js/src/main/javascript/cdf/components/AnalyzerComponent.js
- pentaho-js/src/test/javascript/cdf/components/AnalyzerComponent-spec.js
@pamval, @mbatchelor, @jvelasques, here is backport of https://github.com/webdetails/cdf/pull/880/files to 7.0. Thanks.
> [SP-2985] - Backport of CDF-887 - Date Range input not able to pass parameter correctly to Analyzer component (7.0 Suite)

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/90-AnalyzerComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/90-AnalyzerComponent/template.html
- pentaho-js/src/main/javascript/cdf-legacy/components/Pentaho.Analyzer.js
- pentaho-js/src/main/javascript/cdf/components/AnalyzerComponent.js
- pentaho-js/src/test/javascript/cdf/components/AnalyzerComponent-spec.js
@pamval, @mbatchelor, @jvelasques, here is backport of https://github.com/webdetails/cdf/pull/880/files to 6.1. Thanks.
> [SP-2986] - Backport of CDF-887 - Date Range input not able to pass parameter correctly to Analyzer component (7.0 Suite)

- pentaho/src/main/java/org/pentaho/cdf/environment/broker/PentahoCdfInterPluginBroker.java
@pamval, @mbatchelor, @tgf, could you please take a look?
*should be merged not earlier than: webdetails/cpf#99
> [PPP-3506] - XXE Security Vulnerability in xml parsers

- core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
- core-js/src/main/javascript/cdf/queries/CdaQuery.js
- core-js/src/test/javascript/cdf-legacy/query-spec-legacy.js
- core-js/src/test/javascript/cdf/dashboard/Query-spec.js
> [CDE-849] Export of table with paginate server side set as true is only exporting 10 results in a kettle data source

- core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
- core-js/src/main/javascript/cdf/queries/CdaQuery.js
- core-js/src/test/javascript/cdf-legacy/query-spec-legacy.js
- core-js/src/test/javascript/cdf/dashboard/Query-spec.js
> [SP-3039] Backport of CDE-849 - Export of table with paginate server side set as true is only exporting 10 results in a kettle data source (6.1 Suite)

- core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
- core-js/src/main/javascript/cdf/queries/CdaQuery.js
- core-js/src/test/javascript/cdf-legacy/query-spec-legacy.js
- core-js/src/test/javascript/cdf/dashboard/Query-spec.js
> [SP-3038] Backport of CDE-849 - Export of table with paginate server side set as true is only exporting 10 results in a kettle data source (7.0 Suite)

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/embeddedSample/template.css
- assemblies/cdf/src/main/resources/resources/style/template.css
@pamval @pedrofvteixeira @smaring please take a look
> [CDE-871]-Avoid hardcoding a protocol

- core-js/package.json
- core-js/src/test/javascript/cdf-legacy/components/input-spec-legacy.js
- core-js/src/test/javascript/cdf/components/ButtonComponent-spec.js
- core-js/src/test/javascript/cdf/components/CommentsComponent-spec.js
- core-js/src/test/javascript/cdf/components/MultiButtonComponent-spec.js
- core-js/src/test/javascript/cdf/components/UnmanagedComponent-spec.js
- pentaho-js/package.json
- fixed TypeError errors in tests
- reviewed async tests
- updated the dev dependencies according to changes committed into the master branch
> [TEST] cherry-picking and backporting test environment improvements

- core/pom.xml
- pentaho/pom.xml
- pom.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
> [ENGOPS-2639] json GAV change

- pentaho-js/src/main/javascript/cdf-legacy/components/VisualizationAPIComponent.js
- pentaho-js/src/main/javascript/cdf/components/VisualizationAPIComponent.js
- pentaho-js/src/test/javascript/cdf-legacy/visualization-spec.js
- pentaho-js/src/test/javascript/cdf/components/VisualizationAPIComponent-spec.js
- pentaho-js/src/test/javascript/cdf/mocks/pentaho/type/Context.js
- pentaho-js/src/test/javascript/cdf/mocks/pentaho/visual/base/view.js
@pentaho/millenniumfalcon, @carlosrusso, @graimundo, @marcovala, @davidmsantos90, @nantunes please review.
Depends on pentaho/pentaho-platform-plugin-common-ui#955.
> [BACKLOG-13668] VizAPI views restructuring

- core-js/src/main/javascript/cdf/components/ChartComponent.js
- core-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.js
- core-js/src/test/config/javascript/karma.ci.conf.js
- core-js/src/test/config/javascript/karma.conf.js
- core-js/src/test/javascript/cdf/components/CggComponent.ext.js
- core-js/src/test/javascript/cdf/components/ccc/BaseCccComponent-spec.js
- core-js/src/test/javascript/cdf/components/ccc/BaseCccComponent.ext.js
- core-js/src/test/javascript/cdf/karma.main.js
- core-js/src/test/javascript/cdf/mocks/pentaho/shim/_es6-promise/es6-promise.js
- core-js/src/test/javascript/cdf/mocks/pentaho/shim/es6-promise.js
- pentaho-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.ext.js
- pentaho-js/src/main/javascript/cdf/components/ccc/vizApi.conf.js
- pentaho-js/src/test/javascript/cdf/components/ccc/BaseCccComponent.ext-spec.js
- pentaho-js/src/test/javascript/cdf/mocks/pentaho/type/Context.js
- pentaho-js/src/test/javascript/cdf/mocks/pentaho/visual/color/paletteRegistry.js
@afrjorge @dcleao can you please review the js part?
> [BACKLOG-14077] 

- pentaho-js/src/main/javascript/cdf-pentaho-require-js-cfg.js
- Added require configuration needed for pentaho-require-cfg file
@dcleao please review
> [BACKLOG-14077] 

- pentaho-js/src/main/javascript/cdf-pentaho-require-js-cfg.js
- pentaho-js/src/main/javascript/cdf/components/ccc/config/cdf.vizApi.conf.js
- Added cdf.vizApi config with override for pie chart
@afrjorge @dcleao please review
> [BACKLOG-14077]

- core-js/pom.xml
- core-js/src/doc/javascript/config/jsdoc-cdf.json
- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/tmpl/type.tmpl
@dcleao @carlosrusso @graimundo @nantunes @marcovala @diogofscmariano please review.
Sync with the upgrade done in the https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1031 template . Tested and the documentation was generated correctly
> [BACKLOG-14318] Sync with common-ui template upgrade

- package.json
…er dependencies.
@dcleao Please review
> [BACKLOG-17255] - Fix tests not running due to undeclared required peer dependencies.

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/70-QueryComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/actions/data-for-samples.cda
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/55-CheckComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/66-TemplateComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/70-QueryComponent/template.html
@diogofscmariano sample changes, please review
> [BACKLOG-18456] - Fixing CDF samples

- pentaho/src/main/java/org/pentaho/cdf/embed/EmbeddedHeadersGenerator.java
- pentaho/src/test/java/org/pentaho/cdf/embed/EmbeddedHeadersGeneratorForTests.java
- pentaho/src/test/java/org/pentaho/cdf/embed/EmbeddedHeadersGeneratorTest.java
- CDE's embed js endpoint calls the same CDF endpoint, so those two cases are covered with this commit
> [BACKLOG-16943] Adding environment config to cdf-embed.js

- core-js/src/main/javascript/cdf-legacy/components/input.js
- replace Logger with Dashboards.log usage in CDF legacy version of Text Input Component
> [CDF-985] XSS vulnerability in Text Input Component

- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/DateInputComponent.js
- input value sets through jquery
> [CDF-986] XSS vulnerability in Date Input Component

- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/DateRangeInputComponent.js
- input value sets through jquery
> [CDF-987] XSS vulnerability in Date Range Input Component

- core-js/src/main/javascript/lib/moment/moment.js
> [PPP-3799] Potential use of vulnerable component moment.js 2.9.0

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
> [CDF-983] Eliminated concurrency issue.

- core-js/src/main/javascript/cdf-legacy/lib/mustache/mustache.js
- core-js/src/main/javascript/lib/mustache/mustache.js
- updated mustache.js to 2.2.1 version
> [PPP-3797] Use of vulnerable component mustache.js

- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/DateInputComponent.js
> [SP-3772] Backport of CDF-986 - XSS vulnerability in Date Input Component (7.1 Suite)

- core-js/src/main/javascript/cdf-legacy/lib/mustache/mustache.js
- core-js/src/main/javascript/lib/mustache/mustache.js
- updated mustache.js to 2.2.1 version
> [SP-3801][PPP-3797] Use of vulnerable component mustache.js

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/template.html
- assemblies/cdf/src/main/resources/template-dashboard-mantle-require.html
- assemblies/cdf/src/main/resources/template-dashboard-mantle.html
- assemblies/cdf/src/main/resources/template-dashboard-require.html
- assemblies/cdf/src/main/resources/template-dashboard.html
@pamval @plagoa @marcoslarsen  @francisco-guilherme Please review
> CDF samples - update links from Webdetails/Pentaho to Hitachi Vantara

- core-js/pom.xml
- core-js/src/doc/javascript/config/customPlugins/defineTags.js
- core-js/src/doc/javascript/config/customPlugins/eventHandlers.js
- core-js/src/doc/javascript/config/jsdoc-cdf.json
- core-js/src/doc/javascript/template/publish.js
- core-js/src/doc/javascript/template/static/styles/mindtouch-local.css
- core-js/src/doc/javascript/template/tmpl/amd.tmpl
- core-js/src/doc/javascript/template/tmpl/container.tmpl
- core-js/src/doc/javascript/template/tmpl/details.tmpl
- core-js/src/doc/javascript/template/tmpl/layout.tmpl
- core-js/src/doc/javascript/template/tmpl/methods-summary.tmpl
- core-js/src/doc/javascript/template/tmpl/summary.tmpl
- pom.xml
> [DOC-3679] Sync with the template on common-ui

- pentaho/pom.xml
- pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
> [ENGOPS-1757] version name consolidation

- assemblies/cdf-js/pom.xml
- core-js/pom.xml
- pentaho-js/pom.xml
- pom.xml
Depends on https://github.com/webdetails/ccc/pull/331
> [BACKLOG-20459] Downstream updates

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/pentaho-cdf-require/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
Depends on pentaho/pentaho-platform-plugin-common-ui#1249.
> [BACKLOG-21390] VizAPI 3.0 stock visualizations: Use the new Visual Role's capabilities

- pentaho-js/src/main/javascript/cdf-legacy/components/table.js
- pentaho-js/src/main/javascript/cdf/components/TableComponent.js
> [CDE-943]-Table component that has click action, whenever gets an empty resultset throws an error in jquery.dataTables file.

- core-js/src/test/javascript/cdf-legacy/paralel-query-calls-spec-legacy.js
@webdetails/millenniumfalcon, @joaormf please review.
> [BACKLOG-22244] Fix unit tests

- core-js/src/main/javascript/cdf/components/ccc/BaseCccComponent.js
> [BACKLOG-22074] - Chart rendering according to renderMode

- pentaho-js/src/main/javascript/cdf-legacy/components/table.js
- pentaho-js/src/main/javascript/cdf/components/TableComponent.js
- fixed
- apply fix to legacy version
- updated copyright year
> [SP-4233][CDE-943]-Table component that has click action, whenever gets an empty resultset throws an error in jquery.dataTables file.

- assemblies/cdf/src/main/resources/resources.core.properties
- core-js/src/main/javascript/cdf-legacy/Dashboards.Utils.js
- core-js/src/main/javascript/cdf-legacy/components/input.js
- core-js/src/main/javascript/cdf/components/ToggleButtonBaseComponent.js
- core-js/src/main/javascript/cdf/dashboard/Utils.js
@pamval,  @afrjorge, could you please take a look?
> [CDF-993] - XSS vulnerability in Check Component

- pentaho-js/src/main/javascript/cdf-legacy/components/table.js
- pentaho-js/src/main/javascript/cdf/components/TableComponent.js
- fixed
- apply fix to legacy version
- updated copyright year
> [SP-4232][CDE-943]-Table component that has click action, whenever gets an empty resultset throws an error in jquery.dataTables file.

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/55-CheckComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/58-AutocompleteBoxComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/60-VisualizationAPIComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/64-TableComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/66-TemplateComponent/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/30-documentation/30-component_reference/10-core/70-QueryComponent/template.html
- updated reference to the actions folder
> [BACKLOG-23494] - DEV - Change samples folder structure

- .gitignore
- assemblies/cdf-js/src/main/config/javascript/build.js
- core-js/src/main/javascript/cdf-legacy/queries/xmlaQueries.js
- core-js/src/main/javascript/cdf/queries/BaseQuery.js
- core-js/src/main/javascript/cdf/queries/CdaQuery.js
- core-js/src/main/javascript/cdf/queries/CpkQuery.js
- core-js/src/main/javascript/cdf/queries/SolrQuery.js
- core-js/src/test/javascript/cdf/queries/SolrQuery-spec.js
> [BACKLOG-22048] Foundry CT2000 Dashboard

- assemblies/cdf/src/main/resources/messages_zh_CN.properties
- assemblies/cdf/src/main/resources/resources/languages/messages_supported_languages.properties
- assemblies/cdf/src/main/resources/resources/languages/messages_zh_CN.properties
> [BACKLOG-25043] Simplified Chinese localization

- core/pom.xml
- pentaho/pom.xml
- pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

- core-js/src/main/javascript/cdf/dashboard/Dashboard.i18n.js
- core-js/src/main/javascript/lib/i18n/cdf.jquery.i18n.js
> [BACKLOG-24609][CLEANUP] Code cleanup

- core-js/src/main/javascript/cdf-legacy/queries/coreQueries.js
- core-js/src/main/javascript/cdf/components/UnmanagedComponent.js
- core-js/src/main/javascript/cdf/queries/CdaQuery.js
- pentaho-js/src/main/javascript/cdf-legacy/components/table.js
- pentaho-js/src/main/javascript/cdf/components/TableComponent.js
> [BACKLOG-26349] Handle close message created from error conditions

- assemblies/cdf-js/src/main/config/javascript/build.js
- package-lock.json
- package.json
@webdetails/millenniumfalcon @webdetails/x-wing please review
> [BACKLOG-22832] Upgrade require.js and r.js to version 2.3.6

- pentaho/src/main/java/org/pentaho/cdf/xactions/ActionEngine.java
@pentaho-lmartins @pamval 
@dcleao
> [CDF-1013] ActionEngine.java should use entrySet instead of keySet

- core/src/main/java/org/pentaho/cdf/packager/CdfHeadersProvider.java
@pentaho-lmartins @pamval
@dcleao
> [CDF-1017] CdfDependencyInclusionFilter should be a static class

- pentaho/src/main/java/org/pentaho/cdf/context/ContextEngine.java
@JoaoRPF @JoaoRMF @plagoa @tgf @mbatchelor @pentaho-lmartins Please review.
Reverted this change, unit tests are breaking due to missing spring configs in test context.
> [PPP-4110] - Revert remove static synchronized. Unit tests breaking.

- pentaho/pom.xml
> [BACKLOG-27566] Centralize SLF4J dependency

- pentaho-js/src/main/javascript/cdf-legacy/components/Pentaho.Analyzer.js
- pentaho-js/src/main/javascript/cdf/components/AnalyzerComponent.js
- pentaho-js/src/main/javascript/cdf/components/ExecuteAnalyzerComponent.js
- Mostly cleanup work, the issue was the component not passing the correct path options (solution, path and action) to the api call.
> [BACKLOG-28478] Fix incorrect call to Analyzer on ExecuteAnalyzerReportComponent

- core-js/src/main/javascript/cdf-core-lib-require-js-cfg.js
- core-js/src/main/javascript/lib/moment/moment.js
@tgf @JoaoRPF @JoaoRMF @plagoa Please review.
> [BACKLOG-28353] - Use of Vulnerable Component: moment.js (sonatype-2017-0422 | sonatype-2016-0105). Upgrade moment.js to latest version (2.24.0).

- core-js/src/main/javascript/cdf-core-lib-require-js-cfg.js
@pentaho-lmartins @marcoslarsen
> [BACKLOG-29003] PIR - Textbox prompt, autocomplete does not work

- core-js/src/main/javascript/cdf/README.md
> [CLEANUP] Readme.md was written with html instead of markdown

- core-js/src/main/javascript/cdf-legacy/components/core.js
@pentaho-lmartins @dcleao please review
> [PPP-4008] - Fix calls to discontinued functions/properties

- core-js/src/main/javascript/lib/i18n/cdf.jquery.i18n.js
country level (8.3 Suite)
@RPAraujo @bcostahitachivantara
> [SP-5188] Backport of CDE-1005 - CDE dashboard can't be localized at

- core-js/src/main/javascript/cdf/dashboard/Utils.js
- core-js/src/test/javascript/cdf/dashboard/Utils-spec.js
- pentaho-js/src/main/javascript/cdf/components/XactionComponent.js
- pentaho-js/src/test/javascript/cdf/components/XactionComponent-spec.js
> [PDB-2060] - Xactions cannot be used in Dashboard Designer

- core-js/src/main/javascript/cdf-legacy/components/filter/js/TreeFilter/views/Group.js
- core-js/src/main/javascript/cdf/components/filter/views/Group.js
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Webdetails/cdf/commit/61f0e7c90024f15ec266ae9ced6eab784a9b369d
> [SP-5314] Backport of CDE-1019 - CTools Filter Component renderCollapse function is not working as expected (8.3 Suite)

- core-js/src/main/javascript/lib/theme/cupertino/jquery-ui-1.10.4.custom.css
- core-js/src/main/javascript/lib/theme/smoothness/jquery-ui-1.10.4.custom.css
**Attention: This is the outcome of an automated process!**
Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Webdetails/cdf/commit/02c2269fc8406de5dca4c782cc12e1ba98ee52be
> [SP-5351] Backport of CDE-1029 - CDE - Datasources Panel layout - XPATH Queries not selected (8.3 Suite)

- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/20-samples/blueprint/template.html
- assemblies/cdf-samples/src/main/resources/plugin-samples/pentaho-cdf/legacy/20-samples/blueprint/template.html
Samples required files and components that were removed from the code base.
> [CDF-1028] CDF Blueprint Samples are broken

- assemblies/cdf/src/main/resources/template-dashboard-mantle-require.html
- assemblies/cdf/src/main/resources/template-dashboard-mantle.html
@rmansoor 
@smmribeiro @bcostahitachivantara
> [CDE-1060] CDE links with a no longer existing URL

- core-js/src/main/javascript/cdf/dashboard/Dashboard.i18n.js
@bcostahitachivantara 
@ssamora 
@smmribeiro
> [PDB-1888] 404 error appear in browsers console while creating new dashboard

- core-js/src/main/javascript/cdf/addIns/dataBar/colType/dataBar.js
@ssamora 
@smmribeiro 
@moraesvc
> [CDE-992] - dataBar Addin from Table Component has an incorrect width whenever the value to be represented in the dataBar is 0.

- core-js/src/main/javascript/cdf-legacy/Dashboards.Bookmarks.js
- core-js/src/main/javascript/cdf-legacy/components/ccc.js
- core-js/src/main/javascript/cdf-legacy/lib/pen-shim.js
- core-js/src/main/javascript/cdf/components/ChartComponent.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.bookmarkable.js
- core-js/src/test/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf/queries/CdaQuery.ext.js
@smmribeiro, @ssamora could you please review and merge?
> [CDF-1041] Fix encoding of array query string parameters

- core-js/src/main/javascript/cdf/dashboard/Dashboard.i18n.js
Reverts webdetails/cdf#1128
@bcostahitachivantara @renato-s
> Revert "[SP-6026] Backport of PDB-1888 - 404 error appear in browsers console while creating new dashboard (9.2 Suite)"

- core-js/src/main/javascript/cdf/dashboard/Dashboard.i18n.js
Reverts webdetails/cdf#1129
@bcostahitachivantara @renato-s
> Revert "[SP-6027] Backport of PDB-1888 - 404 error appear in browsers console while creating new dashboard (8.3 Suite)"

- pentaho-js/src/main/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf-legacy/components/Pentaho.Reporting.js
- pentaho-js/src/main/javascript/cdf/components/SchedulePrptComponent.js
[Backlog 30667] - /api/scheduler changes
> [BACKLOG-30667] CSRF - /api/scheduler changes

- core-js/src/main/javascript/cdf/dashboard/Dashboard.i18n.js
@smmribeiro 
@andreramos89 
@renato-s
> [BACKLOG-35785] - CDE dashboard can't be localized at country level

- core-js/src/main/javascript/cdf-legacy/Dashboards.Bookmarks.js
- core-js/src/main/javascript/cdf-legacy/components/ccc.js
- core-js/src/main/javascript/cdf-legacy/lib/pen-shim.js
- core-js/src/main/javascript/cdf/components/ChartComponent.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.bookmarkable.js
- core-js/src/test/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf/queries/CdaQuery.ext.js
@webdetails/sp-branch-write please review and merge.
> [SP-6098] Backport of CDF-1041 - Fix encoding of array query string parameters

- core-js/src/main/javascript/cdf-legacy/Dashboards.Bookmarks.js
- core-js/src/main/javascript/cdf-legacy/components/ccc.js
- core-js/src/main/javascript/cdf-legacy/lib/pen-shim.js
- core-js/src/main/javascript/cdf/components/ChartComponent.js
- core-js/src/main/javascript/cdf/dashboard/Dashboard.bookmarkable.js
- core-js/src/test/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf-legacy/cdf-base.js
- pentaho-js/src/main/javascript/cdf/queries/CdaQuery.ext.js
@webdetails/sp-branch-write please review and merge.
> [SP-6099] Backport of CDF-1041 - Fix encoding of array query string parameters

- core-js/src/main/javascript/lib/xmla/Xmla.js
> [BACKLOG-35904] CSRF - Protect the Request Parameters authentication mechanism

- .gitignore
- core-js/pom.xml
- core-js/src/assembly/assembly.xml
@smmribeiro @befc @miguelappleton 
Related PRs:
https://github.com/webdetails/cde/pull/1046
https://github.com/webdetails/sparkl/pull/95
https://github.com/pentaho/pentaho-platform/pull/5863
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1831
https://github.com/pentaho/maven-parent-poms/pull/684
> chore: use underscore webjar instead of hardcoded file [PPP-5515]

- .gitignore
- core-js/pom.xml
- core-js/src/assembly/assembly.xml
> Revert "chore: use underscore webjar instead of hardcoded file [PPP-5515]"

- assemblies/cdf/pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

- pentaho/src/main/java/org/pentaho/cdf/GetCDFResource.java
Original: https://github.com/webdetails/cdf/pull/1204
> refactor[SP-6861]: stop the GetCDFResource servlet from sending exceptions directly to the client
